import "../app/globals.css"
import {AppProps} from "next/app";
import {ThemeProvider} from "@/components/theme-provider"
import {Metadata} from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function MyApp({ Component, pageProps }: AppProps) {
	return (
		<ThemeProvider
			attribute="class"
			defaultTheme="system"
			enableSystem
			disableTransitionOnChange
		>
			<Component {...pageProps} />
		</ThemeProvider>
	)
}